name: servant-request
version: "0.1"

dependencies:
  - base
  - servant
  - string-conversions
  - bytestring
  - text
  - http-api-data

ghc-options:
  -itest -Wall -fno-warn-name-shadowing

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - servant-request

library:
  source-dirs:
    - src
